### ISSUE TITLE
 [feature]Train Jigsaw for 1000 permutations

### ISSUE THREAD

**Issue by shlokk** [facebookresearch/fair_self_supervision_benchmark#16]
I wanted to train Jigsaw for 1000 and 3000 permutations and was wondering how can I train new Jigsaw models for these permutations?

**Comment by prigoyal** [comment]
Hi @shlokk , thanks for reaching out about this. This repository is primarily for evaluation purposes only and does NOT support pre-training. In due time, we will release the pre-training code as well but that will take some time. 

However, if you are looking for the permutations 1000 and 3000 permutations, we provide script to generate as many permutation as you want. The script is here https://github.com/facebookresearch/fair_self_supervision_benchmark/blob/master/extra_scripts/generate_jigsaw_permutations.py and the instructions are https://github.com/facebookresearch/fair_self_supervision_benchmark/tree/master/extra_scripts#generating-jigsaw-permutations-for-varying-problem-complexity. Hope this helps. :)

**Comment by shlokk** [comment]
Hi, Thanks Priya for the prompt response. 
I was wondering how much time are you estimating to release the code for the pretraining part, as it will allow us to do more experiments in different settings in the benchmark.

**Comment by prigoyal** [comment]
Hi @shlokk, at the moment, it will be a couple months and I recommend to not be blocked by it if you have other codebase you can train on. :)

**Comment by prigoyal** [comment]
Hi @shlokk , I'll be closing out this issue now as it's unrelated to this particular "benchmark" codebase. When we release the pre-training codebase, we'll make an announcement. Stay tuned. In the meantime, feel free to reach out to us for anything!
