### ISSUE TITLE
[bug] Missing make_SN_labels.py?

### ISSUE THREAD

**Issue by BramSW** [facebookresearch/fair_self_supervision_benchmark#26]
The script `make_SN_labels.py` referenced in the **Surface Normal Estimation** README doesn't seem to exist in either of the repositories or data download. I could be mistaken, but I haven't been able to find it with over an hour of searching. Thanks!

**Comment by JayKayKnights** [comment]
I've just run into this problem too - the file definitely seems to be missing!

**Comment by imisra** [comment]
Added the missing file.
