### ISSUE TITLE
Preprocessing COCO - 'minival', 'valminusminival'

### ISSUE THREAD

**Issue by jasonwei20** [facebookresearch/fair_self_supervision_benchmark#29]
What are `minival` and `valminusminival` for the coco dataset? My COCO14 annotations folder looks like this:
```
captions_train2014.json  instances_train2014.json  person_keypoints_train2014.json
captions_val2014.json    instances_val2014.json    person_keypoints_val2014.json
```
Therefore I get an error in when I try to preprocess COCO when running `extra_scripts/create_coco_data_files.py`:
```
partitions = ['val', 'train', 'minival', 'valminusminival']
    for partition in partitions:
```
Do I need `minival` and `valminusminival`?

**Comment by prigoyal** [comment]
Hi @jasonwei20 , thanks for reaching out. Please see the instructions here https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md#coco-minival-annotations for the COCO dataset. Hope this helps.
