### ISSUE TITLE
Pretraining  using a custom subset of Imagenet. 

### ISSUE THREAD

**Issue by chho-work** [facebookresearch/fair_self_supervision_benchmark#30]
Thanks for sharing the code and paper!

I am looking to perform pre-training using Jigsaw(Resnet50) pretext method, just like what was mentioned in the paper(Table 2).  But instead of using Imagenet1K, I would like to pretrained with an Imagenet subset of 10 classes.  I also have only one GPU available.

My question:
1) Is the code for pre-training using Jigsaw(Resenet50) available?  I ask this because I am only seeing codes and commands for Benchmark Tasks and Legacy Tasks.  If pretrained code is available for Jigsaw(Resenet5), pls indicate where I can find them.  

Many thanks and looking forward for your prompt reply!

**Comment by prigoyal** [comment]
Hi @chho-work ,thanks for reaching out about this. We plan to open source a new benchmark version in PyTorch which will also provide pre-training code including the Jigsaw. We will update the README here with the link to the new version. Stay tuned! :)
