### ISSUE TITLE
Evaluating benchmark on simple imagenet pretrained model loaded from PyTorch

### ISSUE THREAD

**Issue by jasonwei20** [facebookresearch/fair_self_supervision_benchmark#31]
I'd like to plug in the PyTorch default ResNet model with ImageNet pretraining to see how it does on the dataset. I'm using the default [`torchvision.models.resnet.ResNet`](https://pytorch.org/docs/stable/_modules/torchvision/models/resnet.html) as my model, but I don't know how to save it in the right format to be read in. In other words, your functions  `save_model_params(model, params_file, checkpoint_dir, model_iter)` and `checkpoints.load_model_from_params_file(model` takes in a model that seems to be a `ModelBuilder` class, and I'd like to load a a model of the class `torchvision.models.resnet.ResNet` . 

Any idea on what the best way to do this is?

Thanks,
Jason

**Comment by prigoyal** [comment]
Hi @jasonwei20 , thanks for reaching out. The way to do this is to convert the model weights to be compatible with the model definition in this github. A script is provided for that https://github.com/facebookresearch/fair_self_supervision_benchmark/blob/master/extra_scripts/pickle_pytorch_to_caffe2.py Hope this helps. Feel free to reach out if there are more questions. :)
